# Generated by Django 4.1.7 on 2023-03-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_item_report', '0002_reportlostitem_alter_founditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlostitem',
            name='model_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
