# Generated by Django 4.1.7 on 2023-03-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_item_report', '0003_reportlostitem_model_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportlostitem',
            old_name='name',
            new_name='item_name',
        ),
    ]
