# Generated by Django 4.1.7 on 2023-03-12 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lost_item_report', '0004_rename_name_reportlostitem_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlostitem',
            name='item_category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='lost_item_report.itemcategory'),
            preserve_default=False,
        ),
    ]
