# Generated by Django 4.1.7 on 2023-03-18 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lost_item_report', '0006_remove_founditem_claimed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
