# Generated by Django 4.1.7 on 2023-03-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_item_report', '0007_founditem_claimed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='claimed_date',
        ),
    ]
