# Generated by Django 4.1.7 on 2023-03-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_item_report', '0008_remove_founditem_claimed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='claimed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
