# Generated by Django 4.1.7 on 2023-03-18 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lost_item_report', '0009_founditem_claimed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClaimItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('attachment', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='claimed_by_user', to=settings.AUTH_USER_MODEL)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lost_item_report.founditem')),
            ],
        ),
    ]
