# Generated by Django 4.1.7 on 2023-05-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_item_report', '0010_userclaimitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='post_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
