# Generated by Django 4.2.1 on 2023-05-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_item_report', '0010_userclaimitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userclaimitem',
            options={'verbose_name': 'My Claim Item'},
        ),
        migrations.AddField(
            model_name='founditem',
            name='post_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='founditem',
            name='post_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userclaimitem',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing State'), ('in_review', 'Under Review'), ('approved', 'Approved')], default='processing', max_length=20),
        ),
    ]
