# Generated by Django 4.2.1 on 2023-05-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_item_report', '0011_alter_userclaimitem_options_founditem_post_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='post_limit',
            field=models.IntegerField(default=1),
        ),
    ]
