# Generated by Django 4.2.1 on 2023-05-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_item_report', '0011_founditem_post_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclaimitem',
            name='status',
            field=models.CharField(choices=[('processing', 'Claim in Processing State'), ('in_review', 'Claim currently under review'), ('approved', 'Claim approved')], default='processing', max_length=20),
        ),
    ]
