# Generated by Django 4.2.1 on 2023-06-22 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lost_item_report.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lost_item_report', '0012_alter_founditem_post_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userclaimitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='post_limit',
        ),
        migrations.AddField(
            model_name='founditem',
            name='is_admin_approved',
            field=models.BooleanField(default=False, help_text='Only This field value true Found Item will be shown on frontend list'),
        ),
        migrations.AddField(
            model_name='reportlostitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportlostitem',
            name='reported_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='reported_lost_item_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportlostitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lost_item_report.utils.get_upload_path),
        ),
    ]
