# Generated by Django 4.2.1 on 2023-06-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_item_report', '0012_userclaimitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='is_admin_approved',
            field=models.BooleanField(default=False, help_text='After Admin Approval Found Item will be shown on frontend list'),
        ),
        migrations.AlterField(
            model_name='userclaimitem',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing State'), ('in_review', 'Under Review'), ('approved', 'Approved')], default='processing', max_length=20),
        ),
    ]
