# Generated by Django 4.2.1 on 2023-06-10 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lost_item_report', '0014_remove_reportlostitem_reporter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlostitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportlostitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
